---
- block:
  - name: Install just
    package:
      name: just
    become: true

  - name: Setup just zsh completion
    command: stow -v -t ~ -d {{ role_path }}/files -S . --no-folding
    register: output
    changed_when: '"LINK" in output.stderr'

  tags:
  - just
