---
compile_vim_git_dest: /tmp/vim
compile_vim_configure_prefix: /usr/local
compile_vim_deps:
  apt:
  - libncurses-dev
  - xorg-dev          # for +clipboard
  - cmake
  - lua5.3            # for +lua
  - liblua5.3-dev       # for +lua
  - python3           # for +python3/dyn
  - libpython3-dev       # for +python3/dyn
  pacman:
  - base-devel
  - make
  - cmake
  - gcc
  - awk
  - ncurses
  - libx11
  - xorg-xinit
  - lua5.3            # for +lua
  - liblua5.3-dev       # for +lua
  - python3           # for +python3/dyn
  - libpython3-dev       # for +python3/dyn
